### ISSUE TITLE
`$CXXFLAGS` Environment variable

### ISSUE THREAD

**Issue by bfarzin** [lu-kie/PALMS_ImagePartitioning#1]
Hi. I don't build CPP projects so I don't have a default `$CXXFLAGS` set in my environment.
This is called in the `build.m` file.  What do I need to build this project?

**Comment by lu-kie** [comment]
Hi Bobak, to build the mex file in Matlab with the g++ compiler you need the openMP and the armadillo library which can be installed via your package manager (e.g. for ubuntu: libarmadillo-dev, libomp-dev) . When the mex file has been successfully built, the demo should be working. Maybe it is necessary that you change the default C++ compiler in matlab to g++ via "mex -setup cpp".
Best, Lukas
